### ISSUE TITLE
/ ï / et / Ï / à la place de / ì / et / Ì /

### ISSUE THREAD

**Issue by valsou** [julienblitte/qwerty-fr#4]
Bonjour,

ne serait-il pas plus pratique de placer les lettres / ï / et / Ï / (touche K) à la place de / ì / et / Ì / (touche I) par défaut ? Le tréma me semble beaucoup plus courant que l'accent grave.

À part ça je viens juste d'installer votre disposition de touches et je la trouve excellente. Merci beaucoup !

**Comment by julienblitte** [comment]
Bonjour Valentin,

Merci pour ce retour.

L'emplacement des touches est toujours discutable ainsi que le choix de
certains caractères, mais il faut considérer plusieurs choses :
- Le clavier utilise une logique d'emplacement des diacritiques pour
faciliter son apprentissage et son utilisation ;
- Du coup pour faire ce changement, il faudrait changer également la
modification des lettres ë/è, ÿ, ü, ï/ì, ò/ö et à/ä pour respecter la
philosophie ;
- Si on suit cette même logique, on perdrait la touche directe ÿ qui est
une lettre utilisée en Français contrairement au ỳ qui n'est pas utilisé en
Français mais pour d'autres langues (gallois, timbira et vietnamien d'après
Wikipedia) ;
- Le clavier a maintenant un petit nombre d'utilisateurs au travers du
monde (impossible de savoir approximativement combien mais au alentours
d'une centaine je dirais) et un tel changement impliquerait qu'ils doivent
ré-apprendre cette nouvelle disposition.

Bien entendu, grâce aux sources, il est tout à fait possible de faire sa
propre version personnalisée si besoin.

Julien Blitte


Le mar. 9 juin 2020 à 10:13, Valentin MEZIN <notifications@github.com> a
écrit :

**Comment by valsou** [comment]
Merci pour la réponse rapide.

Je pensais plutôt à une exception à la française. :o
Mais je comprends totalement la philosophie de ta disposition et effectivement ce sera pas évident pour tout le monde.

Je vais voir pour personnaliser tout ça.
Encore merci. :)
