### ISSUE TITLE
Integration with gnome (ubuntu 20.04)

### ISSUE THREAD

**Issue by SeguinBe** [julienblitte/qwerty-fr#5]
Hello,

Le layout n'apparaît pas pour moi dans l'interface des settings pour un Ubuntu 20.04 nouvellement installé.

J'ai pu l'activer avec `setxkbmap`, mais par contre il semble que le layout Gnome est complétement oublié maintenant (nottament si je change de layout avec le raccourci clavier).

Quelqu'un a rencontré ça?

**Comment by julienblitte** [comment]
Bonjour,

Cela très longtemps que j'ai du passé sur Windows pour le travail
malheuresement, je n'utilise GNU/Linux qu'en lignes de commandes de temps
en temps.

Est-ce que l'on sait depuis quelle version de Ubuntu ou de Gnome on a perdu
la compatibilité ?

Il faudra que je monte une machine virtuelle pour comprendre le problème.
L'idéal serait à terme d'intégrer le layout directement dans ceux par
défaut d'Ubuntu.

Julien Blitte

Le jeu. 11 juin 2020 à 12:23, Benoit Seguin <notifications@github.com> a
écrit :

**Comment by SeguinBe** [comment]
Hello,

J'y ai rejeté un oeil récemment et tout marche...

Je sais pas si j'avais mal cherché à l'époque (genre dans la section English au lieu de French) ou autre, mais en tout cas tout marche :+1: 

![Screenshot from 2020-06-24 19-10-12](https://user-images.githubusercontent.com/7132817/85601167-6b2c6f80-b64e-11ea-8e2a-94c7a66c61ea.png)
